### ISSUE TITLE
NLP-Insights - POST/PUT operations not consistent with other health-patterns services

### ISSUE THREAD

**Issue by rguderian** [LinuxForHealth/health-patterns#229]
For other health-patterns services, the POST/PUT convention has been:  
1. POST operations to be create-only.  An error is returned if the config already exists.
2. PUT operation create if the config does not exist or update if the config exists

For NLP-Insights, POST/PUT operation behave like item 2 above.

Should all health-patterns services be consistent with POST/PUT operations?

**Comment by ranum** [comment]
Fixed in latest nlp-insights code
