### ISSUE TITLE
Create a Chart repository

### ISSUE THREAD

**Issue by luisgarcc** [LinuxForHealth/health-patterns#54]
We include the tgz version of our dependent charts (e.g. nifi, zookeeper, kafka, etc.) in order to facilitate users deploying our main chart.

By including the tgzs a user just needs to git clone the repo and they can helm install right away.

If we don't include the tgzs users need to run an extra couple of commands to add the repositories where the dependent charts live and another command to update the local deps based on the repos that were just added.

When we run ct lint though, the ct lint command does not recognize the tgz version of the charts, it needs to either add/update/install the dependencies or get them from source. This means that if we removed the deid chart's source from our health-patterns repo, now that it officially lives in the de-identification repo the ct lint command would fail because it would not know where to get the deid chart from (since it currently does not live in any repo).

The purpose of this card is to:
- Work with the de-id team move their chart into an actual repository (e.g. Github allows creating chart repos) where we can reference it for linting
- Update our repository to get rid of the original source and ensure linting works pointing to the new repo

[Here](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417) is a nice article on how to do that with Github pages.

**Comment by ewill00** [comment]
We have a chart repo now.  The only part of this issue that remains is to have deid make their chart available in the repo
