### ISSUE TITLE
Better error reporting granularity from the Custom Processors

### ISSUE THREAD

**Issue by luisgarcc** [LinuxForHealth/health-patterns#81]
The deidentify and translation custom processors that accept Bundles can act on individual resources within a bundle, and those actions on the individual resources may fail. The purpose of this issue is to enhance them so that the errors are reported individually and the custom processors process what they can instead of failing the whole Bundle.

**Comment by ewill00** [comment]
Isn't this the same as  https://github.com/Alvearie/health-patterns/issues/70
